version: '3.1'

services:
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    env_file:
      - ./.env

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 60 1
    volumes:
      - ./rdata:/rdata
      - ./docker_datas/redis.conf:/usr/local/etc/redis/redis.conf
    env_file:
      - ./.env

  storage:
    image: akashmondal0/sky-storage:latest
    restart: always
    ports:
      - 4001:4001
    container_name: storage
    volumes:
      - ./storage:/app/storage
    env_file:
      - ./.env

  app:
    image: akashmondal0/react-native-backend:latest
    restart: always
    ports:
      - 4000:4000
    env_file:
      - ./.env
  
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.11-1.1.1
    ports:
      - "9092:9092"
    links:
      - zookeeper
    env_file:
      - ./.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  prom-server:
    image: prom/prometheus
    restart: always
    ports:
      - 9090:9090
    volumes:
      - ./prometheus-config.yml:/etc/prometheus/prometheus.yml
  
  grafana:
    image: grafana/grafana-oss:latest
    restart: always
    ports:
      - "3000:3000"

  grafana-loki:
    image: grafana/loki:latest
    restart: always
    ports:
      - "3100:3100"

