version: '3.1'

services:
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: akash1234
      MONGO_INITDB_DATABASE: chatapp

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 60 1
    volumes:
      - ./rdata:/rdata
      - ./docker_datas/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      REDIS_PASSWORD: akash1234
      REDIS_PORT: 6379
      REDIS_DATABASES: 1
